# Generated by Django 2.2.7 on 2020-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_yandex_maps', '0008_auto_20200310_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexmaps',
            name='height',
            field=models.IntegerField(default=400, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='yandexmaps',
            name='sizing',
            field=models.CharField(choices=[('aspect', 'Keep aspect'), ('static', 'Static'), ('static_height', 'Min height and full width'), ('auto', 'Auto')], default='static_height', max_length=100, verbose_name='Sizing'),
        ),
    ]
